import { User } from './db.types';

const avatar = (n: number) => `https://i.pravatar.cc/300?img=${n}`;

export const USERS: User[] = [
  {
    id: 'u-adam',
    username: 'adam_ondra',
    email: 'adam@kordo.app',
    firstName: 'Adam',
    lastName: 'Ondra',
    isSetter: false,
    avatarUrl:
      'https://res.cloudinary.com/dqmegz5dn/image/upload/v1763334248/avatar-kordo_rwvjw4.png',
    bio: 'Toujours un projet en cours 🧗',
    createdAt: '2024-01-12',
    updatedAt: '2025-05-20',
  },
  {
    id: 'u-janja',
    username: 'janja',
    email: 'janja@kordo.app',
    firstName: 'Janja',
    lastName: 'Garnbret',
    isSetter: false,
    avatarUrl: avatar(5),
    bio: 'Bloc & difficulté',
    createdAt: '2024-02-03',
    updatedAt: '2025-05-18',
  },
  {
    id: 'u-shauna',
    username: 'shauna_c',
    email: 'shauna@kordo.app',
    firstName: 'Shauna',
    lastName: 'Coxsey',
    isSetter: false,
    avatarUrl: avatar(9),
    createdAt: '2024-02-15',
    updatedAt: '2025-04-30',
  },
  {
    id: 'u-tomoa',
    username: 'tomoa',
    email: 'tomoa@kordo.app',
    firstName: 'Tomoa',
    lastName: 'Narasaki',
    isSetter: false,
    avatarUrl: avatar(12),
    createdAt: '2024-03-01',
    updatedAt: '2025-05-10',
  },
  {
    id: 'u-leo',
    username: 'leo_climbs',
    email: 'leo@kordo.app',
    firstName: 'Léo',
    lastName: 'Martin',
    isSetter: false,
    avatarUrl: avatar(15),
    bio: 'Grimpeur du week-end',
    createdAt: '2024-03-22',
    updatedAt: '2025-05-21',
  },
  {
    id: 'u-emma',
    username: 'emma_b',
    email: 'emma@kordo.app',
    firstName: 'Emma',
    lastName: 'Bernard',
    isSetter: false,
    avatarUrl: avatar(20),
    createdAt: '2024-04-05',
    updatedAt: '2025-05-19',
  },
  {
    id: 'u-hugo',
    username: 'hugo_p',
    email: 'hugo@kordo.app',
    firstName: 'Hugo',
    lastName: 'Petit',
    isSetter: false,
    avatarUrl: avatar(33),
    createdAt: '2024-04-18',
    updatedAt: '2025-05-17',
  },
  {
    id: 'u-chloe',
    username: 'chloe_g',
    email: 'chloe@kordo.app',
    firstName: 'Chloé',
    lastName: 'Garcia',
    isSetter: false,
    avatarUrl: avatar(25),
    createdAt: '2024-05-02',
    updatedAt: '2025-05-15',
  },
  {
    id: 'u-nina',
    username: 'nina_setter',
    email: 'nina@kordo.app',
    firstName: 'Nina',
    lastName: 'Lopez',
    isSetter: true,
    avatarUrl: avatar(45),
    bio: 'Ouvreuse @ Arkose Nation',
    createdAt: '2023-11-10',
    updatedAt: '2025-05-22',
  },
  {
    id: 'u-marco',
    username: 'marco_setter',
    email: 'marco@kordo.app',
    firstName: 'Marco',
    lastName: 'Rossi',
    isSetter: true,
    avatarUrl: avatar(51),
    bio: 'Ouvreur, fan de dalle',
    createdAt: '2023-12-01',
    updatedAt: '2025-05-22',
  },
  {
    id: 'u-sarah',
    username: 'sarah_k',
    email: 'sarah@kordo.app',
    firstName: 'Sarah',
    lastName: 'Khan',
    isSetter: false,
    avatarUrl: avatar(31),
    createdAt: '2024-05-20',
    updatedAt: '2025-05-12',
  },
  {
    id: 'u-tom',
    username: 'tom_d',
    email: 'tom@kordo.app',
    firstName: 'Tom',
    lastName: 'Dubois',
    isSetter: false,
    avatarUrl: avatar(60),
    createdAt: '2024-06-08',
    updatedAt: '2025-05-09',
  },
];

export const getUserById = (id: string): User | undefined => USERS.find((u) => u.id === id);

// Utilisateur courant simulé (celui connecté dans l'app)
export const CURRENT_USER: User = USERS[4];
